# Generated by Django 4.2.3 on 2023-07-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
    ]
