# Generated by Django 4.2.3 on 2023-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_remove_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
