# Generated by Django 4.2.3 on 2023-07-13 17:58

import Apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_alter_catagory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=Apps.models.getfilename)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('trending_Mobiles', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('trending_Fashion', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('trending_Electronics', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('trending_HomeFurniture', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('trending_Appliances', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('trending_ToysBeauty', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('trending_Grocery', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('quandity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
