# Generated by Django 4.2.3 on 2023-07-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_trendingproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='trending_Appliances',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_Electronics',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_Fashion',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_Grocery',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_HomeFurniture',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_Mobiles',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_ToysBeauty',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
    ]
