# Generated by Django 4.2.3 on 2023-07-16 10:24

import Apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=Apps.models.getfilename),
        ),
    ]
