# Generated by Django 4.2.3 on 2023-07-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0011_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quandity',
            new_name='quantity',
        ),
    ]
