# Generated by Django 4.2.3 on 2023-07-30 13:13

import Apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0018_recentview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainproductimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('product_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=Apps.models.getfilename)),
            ],
        ),
    ]
