# Generated by Django 4.2.3 on 2023-07-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0019_mainproductimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mainproductimg',
            new_name='Highliteimg',
        ),
    ]
