# Generated by Django 4.2.3 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0022_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='todays_deal',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
    ]
