# Generated by Django 4.2.3 on 2023-08-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0023_product_todays_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highliteimg',
        ),
    ]
