# Generated by Django 4.2.3 on 2023-08-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0024_delete_highliteimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='trending_HomeFurniture',
            new_name='trending_Sports',
        ),
    ]
